Update cateye

diff --git a/cateye b/cateye
--- a/cateye
+++ b/cateye
@@ -239,7 +239,7 @@ get_os() {
 
 get_latest_version() {
     local latest_version
-    latest_version=$(curl -sS https://dl.kamu.jp/cateye/version.html)
+    latest_version=$(curl -sS https://github.com/Kamu-JP/cateye/raw/main/version.txt)
     echo "$latest_version"
 }
 
@@ -376,7 +376,7 @@ case "$command" in
             logging "info" "Updating Cateye: $current_script"
             current_script="$0"
             logging "info" "Downloading latest script to $current_script"
-            curl -sS -o "$current_script" "https://dl.kamu.jp/cateye/cateye" || { logging "error" "Failed to download latest script"; exit 1; }
+            curl -sS -o "$current_script" "https://github.com/Kamu-JP/cateye/raw/main/cateye" || { logging "error" "Failed to download latest script"; exit 1; }
             chmod +x "$current_script"
             logging "checkmark" "Updated successfully."
         fi
