Update cateye

diff --git a/cateye b/cateye
--- a/cateye
+++ b/cateye
@@ -1,28 +1,28 @@
 #!/bin/bash
 
-cateyeversion="5.7.0"
-cateyechanges="Added prompt for running setup script"
+cateyeversion="5.8.0"
+cateyechanges="Updated color of logging"
 
 # Extract command and package name from argument
 command="$1"
 
 download_and_install() {
     local url="$1"
-    logging "info" "Download $url" "cyan"
+    logging "info" "Download $url"
     local filename
     filename=$(basename "$url")
-    curl -LO "$url" || { logging "error" "Failed to download: $url" "red"; exit 1; }
-    logging "info" "Unzip: $filename" "cyan"
-    tar -xzf "$filename" || { logging "error" "Failed to extract $filename" "red"; rm "$filename"; exit 1; }
+    curl -LO "$url" || { logging "error" "Failed to download: $url" ; exit 1; }
+    logging "info" "Unzip: $filename"
+    tar -xzf "$filename" || { logging "error" "Failed to extract $filename" ; rm "$filename"; exit 1; }
     rm "$filename"
     # Assuming the extracted folder contains binaries to add to system bin directory
-    logging "info" "Installing file: $filename" "cyan"
-    sudo cp -r "./$package_name" "/usr/local/bin/" || { logging "error" "Failed to install $filename" "red"; rm "./$package_name"; exit 1; }
+    logging "info" "Installing file: $filename"
+    sudo cp -r "./$package_name" "/usr/local/bin/" || { logging "error" "Failed to install $filename" ; rm "./$package_name"; exit 1; }
     rm "./$package_name"
-    logging "info" "Setting file: $filename" "cyan"
+    logging "info" "Setting file: $filename"
     chmod +x "/usr/local/bin/$package_name"
     printf "\e[34m[+]\e[0m installed: $package_name\n"
-    logging "info" "installed: $package_name" "cyan"
+    logging "info" "installed: $package_name"
 }
 
 logging() {
@@ -35,14 +35,14 @@ logging() {
         "red")
             color_code="31m"
             ;;
+        "green")
+            color_code="32m"
+            ;;
         "orange")
             color_code="33m"
             ;;
         "yellow")
             color_code="33m"
-            ;;
-        "green")
-            color_code="32m"
             ;;
         "cyan")
             color_code="36m"
@@ -54,7 +54,24 @@ logging() {
             color_code="35m"
             ;;
         *)
+
             color_code="0m"
+
+            case $mode in
+                "step")
+                    color_code="35m"
+                    ;;
+                "info")
+                    color_code="36m"
+                    ;;
+                "warn")
+                    color_code="33m"
+                    ;;
+                "error")
+                    color_code="31m"
+                    ;;
+            esac
+
             ;;
     esac
     case $mode in
@@ -95,25 +112,25 @@ install_dependencies() {
     
     package_url="$1"
     json_url="$package_url"
-    pkg_json=$(curl -sS "$json_url") || { logging "error" "Failed to retrieve JSON File from $json_url" "red"; exit 1; }
+    pkg_json=$(curl -sS "$json_url") || { logging "error" "Failed to retrieve JSON File from $json_url" ; exit 1; }
     package_name=$(echo "$pkg_json" | jq -r '.name')
     dependencies=$(echo "$pkg_json" | jq -r '.dependencies | to_entries[] | .value')
     for url in $dependencies; do
-        logging "info" "Found external JSON File in JSON File: $url" "cyan"
+        logging "info" "Found external JSON File in JSON File: $url"
         install_dependencies "$url"
     done
     os_id=$(get_os)
     target_key="$os_id"
     result=$(echo "$pkg_json" | jq ". | has(\"$target_key\")")
     if [ "$result" == "true" ]; then
-        logging "info" "Found dependencies url in JSON File: $url_of_software_for_this_os" "cyan"
+        logging "info" "Found dependencies url in JSON File: $url_of_software_for_this_os"
         download_and_install "$url_of_software_for_this_os"
     else
         main_url=$(echo "$pkg_json" | jq -r '.url')
-        logging "info" "Found dependencies url in JSON File: $main_url" "cyan"
+        logging "info" "Found dependencies url in JSON File: $main_url"
         download_and_install "$main_url"
     fi
-    logging "step" "Running setup script for '$package_name'..." "purple"
+    logging "step" "Running setup script for '$package_name'..." 
     runscript=true
     allow_running_script=true
     scripts=$(echo "$pkg_json" | jq -r '.script | to_entries[] | .value') || { printf "\e[31m[!]\e[0m Skip this because there is no setup script.\n"; runscript=false; }
@@ -121,13 +138,13 @@ install_dependencies() {
         true)
 
             for script in $scripts; do
-                logging "step" "Running setup script: '$script'..." "purple"
+                logging "step" "Running setup script: '$script'..." 
                 eval "$script"
             done
 
             ;;
         *)
-            logging "step" "Skip Running Install script." "yellow"
+            logging "step" "Skip Running Install script." 
             ;;
     esac
 
@@ -176,15 +193,15 @@ case "$command" in
         latest_version=$(get_latest_version)
         if [[ "$cateyeversion" == "$latest_version" ]]; then
             echo "Current: cateye V$cateyeversion (Up to date)"
-            logging "info" "No update." "cyan"
+            logging "info" "No update."
         else
             echo "Current: cateye V$cateyeversion (latest: V$latest_version)"
-            logging "info" "Updating Cateye: $current_script" "cyan"
+            logging "info" "Updating Cateye: $current_script"
             current_script="$0"
-            logging "info" "Downloading latest script to $current_script" "cyan"
+            logging "info" "Downloading latest script to $current_script"
             curl -sS -o "$current_script" "https://dl.kamu.jp/cateye/cateye" || { printf "\e[31m[!] Failed to download latest script\e[0m\n"; exit 1; }
             chmod +x "$current_script"
-            logging "info" "Updated successfully." "cyan"
+            logging "info" "Updated successfully."
         fi
         ;;
     "version")
@@ -195,44 +212,44 @@ case "$command" in
         else
             echo "cateye V$cateyeversion (latest: V$latest_version)"
         fi
-        logging "step" "OS" "purple"
+        logging "step" "OS" 
         echo "OS: $os_id"
-        logging "step" "PATH of Cateye" "purple"
+        logging "step" "PATH of Cateye" 
         echo "PATH: $0"
-        logging "step" "Update of This version" "purple"
-        logging "info" "$cateyechanges" "cyan"
+        logging "step" "Update of This version" 
+        logging "info" "$cateyechanges"
         ;;
     "install")
 
         if [ -n "$1" ]; then
-            logging "info" "The number of arguments is normal. Start the installation." "cyan"
+            logging "info" "The number of arguments is normal. Start the installation."
         else
-            logging "error" "Not enough arguments" "red"
+            logging "error" "Not enough arguments" 
             exit 1
         fi
 
         os_id=$(get_os)
         package_name="$2"
-        logging "step" "Start the installation." "purple"
+        logging "step" "Start the installation." 
         json_url="https://dl.kamu.jp/$package_name/pkg.json"
         pkg_json=$(curl -sS "$json_url") || { logging "error" "Failed to retrieve JSON File from $json_url"; exit 1; }
         dependencies=$(echo "$pkg_json" | jq -r '.dependencies | to_entries[] | .value')
         for url in $dependencies; do
-            logging "info" "Found external JSON File in JSON File: $url" "cyan"
+            logging "info" "Found external JSON File in JSON File: $url"
             install_dependencies "$url"
         done
         os_id=$(get_os)
         target_key="$os_id"
         result=$(echo "$pkg_json" | jq ". | has(\"$target_key\")")
         if [ "$result" == "true" ]; then
-            logging "info" "Found Main url in JSON File: $url_of_software_for_this_os" "cyan"
+            logging "info" "Found Main url in JSON File: $url_of_software_for_this_os"
             download_and_install "$url_of_software_for_this_os"
         else
             main_url=$(echo "$pkg_json" | jq -r '.url')
-            logging "info" "Found Main url in JSON File: $main_url" "cyan"
+            logging "info" "Found Main url in JSON File: $main_url"
             download_and_install "$main_url"
         fi
-        logging "step" "Running setup script for '$package_name'..." "purple"
+        logging "step" "Running setup script for '$package_name'..." 
         runscript=true
         allow_running_script=true
         scripts=$(echo "$pkg_json" | jq -r '.script | to_entries[] | .value') || { printf "\e[31m[!]\e[0m Skip this because there is no setup script.\n"; runscript=false; }
@@ -244,70 +261,70 @@ case "$command" in
                     y)
                         runscript=true
                         for script in $scripts; do
-                            logging "step" "Running setup script: '$script'..." "purple"
+                            logging "step" "Running setup script: '$script'..." 
                             eval "$script"
                         done
                         ;;
                     n)
                         runscript=false
                         allow_running_script=false
-                        logging "step" "Skip Running Install script." "yellow"
+                        logging "step" "Skip Running Install script." 
                         ;;
                     *)
-                        logging "error" "Unknown answer, continue the installation with running the setup script." "red"
+                        logging "error" "Unknown answer, continue the installation with running the setup script." 
                         runscript=true
                         ;;
                 esac
                 ;;
             *)
-                logging "step" "Skip Running Install script." "yellow"
+                logging "step" "Skip Running Install script." 
                 ;;
         esac
-        logging "step" "Done." "purple"
+        logging "step" "Done." 
         latest_version=$(get_latest_version)
         if [[ "$cateyeversion" != "$latest_version" ]]; then
-            logging "warn" "A newer version is available: V$latest_version" "yellow"
-            logging "warn" "Consider running: cateye update" "yellow"
+            logging "warn" "A newer version is available: V$latest_version" 
+            logging "warn" "Consider running: cateye update" 
         fi
 
         if [ "$allow_running_script" == "false" ]; then
-            logging "warn" "Skiped setup script, because you answered 'n'. if you want to run the setup script, run the following command." "yellow"
-            logging "warn" "cateye install $package_name" "yellow"
+            logging "warn" "Skiped setup script, because you answered 'n'. if you want to run the setup script, run the following command." 
+            logging "warn" "cateye install $package_name" 
         fi
 
-        logging "info" "Installation of $package_name and that dependencies completed successfully" "cyan"
+        logging "info" "Installation of $package_name and that dependencies completed successfully"
 
         ;;
     "url")
         if [ -n "$2" ]; then
-            logging "info" "The number of arguments is normal. Start the installation from the URL." "cyan"
+            logging "info" "The number of arguments is normal. Start the installation from the URL."
         else
-            logging "error" "Not enough arguments" "red"
+            logging "error" "Not enough arguments" 
             exit 1
         fi
         package_url="$2"
-        logging "step" "Running from the URL." "purple"
+        logging "step" "Running from the URL." 
         json_url="$package_url"
-        pkg_json=$(curl -sS "$json_url") || { logging "error" "Failed to retrieve JSON File from $json_url" "red"; exit 1; }
+        pkg_json=$(curl -sS "$json_url") || { logging "error" "Failed to retrieve JSON File from $json_url" ; exit 1; }
         package_name=$(echo "$pkg_json" | jq -r '.name')
         dependencies=$(echo "$pkg_json" | jq -r '.dependencies | to_entries[] | .value')
         for url in $dependencies; do
-            logging "info" "Found external JSON File in JSON File: $url" "cyan"
+            logging "info" "Found external JSON File in JSON File: $url"
             install_dependencies "$url"
         done
         os_id=$(get_os)
         target_key="$os_id"
         result=$(echo "$pkg_json" | jq ". | has(\"$target_key\")")
         if [ "$result" == "true" ]; then
-            logging "info" "Found Main url in JSON File: $url_of_software_for_this_os" "cyan"
+            logging "info" "Found Main url in JSON File: $url_of_software_for_this_os"
             download_and_install "$url_of_software_for_this_os"
         else
             main_url=$(echo "$pkg_json" | jq -r '.url')
-            logging "info" "Found Main url in JSON File: $main_url" "cyan"
+            logging "info" "Found Main url in JSON File: $main_url"
             download_and_install "$main_url"
         fi
 
-        logging "step" "Running setup script for '$package_name'..." "purple"
+        logging "step" "Running setup script for '$package_name'..." 
         runscript=true
         allow_running_script=true
         scripts=$(echo "$pkg_json" | jq -r '.script | to_entries[] | .value') || { printf "\e[31m[!]\e[0m Skip this because there is no setup script.\n"; runscript=false; }
@@ -319,39 +336,39 @@ case "$command" in
                     "y")
                         runscript=true
                         for script in $scripts; do
-                            logging "step" "Running setup script: '$script'..." "purple"
+                            logging "step" "Running setup script: '$script'..." 
                             eval "$script"
                         done
                         ;;
                     "n")
-                        logging "step" "Skip Running Install script." "yellow"
+                        logging "step" "Skip Running Install script." 
                         runscript=false
                         allow_running_script=false
                         ;;
                     *)
-                        logging "error" "Unknown answer, continue the installation with running the setup script." "red"
+                        logging "error" "Unknown answer, continue the installation with running the setup script." 
                         runscript=true
                         ;;
                 esac
 
                 ;;
             *)
-                logging "step" "Skip Running Install script." "yellow"
+                logging "step" "Skip Running Install script." 
                 ;;
         esac
-        logging "step" "Done." "purple"
+        logging "step" "Done." 
         latest_version=$(get_latest_version)
         if [[ "$cateyeversion" != "$latest_version" ]]; then
-            logging "warn" "A newer version is available: V$latest_version" "yellow"
-            logging "warn" "Consider running: cateye update" "yellow"
+            logging "warn" "A newer version is available: V$latest_version" 
+            logging "warn" "Consider running: cateye update" 
         fi
 
         if [ "$allow_running_script" == "false" ]; then
-            logging "warn" "Skiped setup script, because you answered 'n'. if you want to run the setup script, run the following command." "yellow"
-            logging "warn" "cateye url $package_url" "yellow"
+            logging "warn" "Skiped setup script, because you answered 'n'. if you want to run the setup script, run the following command." 
+            logging "warn" "cateye url $package_url" 
         fi
 
-        logging "info" "Installation of $package_name and that dependencies completed successfully" "cyan"
+        logging "info" "Installation of $package_name and that dependencies completed successfully"
         ;;
 
     "cedk")
@@ -404,7 +421,7 @@ EOF
         fi
 
         echo " "
-        logging "step" "Usage" "purple"
+        logging "step" "Usage" 
         echo "Update:"
         echo " cateye update"
         echo "Run CEDK(Cateye Development Kit):"
