Update cateye

diff --git a/cateye b/cateye
--- a/cateye
+++ b/cateye
@@ -1,7 +1,7 @@
 #!/bin/bash
 
-cateyeversion="5.3.0"
-cateyechanges="Built-in Cateye Development Kit\n"
+cateyeversion="5.4.0"
+cateyechanges="URL install is now not need to specify the package name!"
 
 # Check if running with sudo
 if [ "$EUID" -ne 0 ]; then
@@ -14,41 +14,70 @@ command="$1"
 
 download_and_install() {
     local url="$1"
-    printf "\e[35m [+]\e[0m download $url\n"
+    logging "info" "Download $url" "cyan"
     local filename
     filename=$(basename "$url")
-    curl -LO "$url" || { printf "\e[31m [!]\e[0m Failed to download: $url\n"; exit 1; }
-    printf "\e[35m [+]\e[0m unzip: $filename\n"
-    tar -xzf "$filename" || { printf "\e[31m [!]\e[0m Failed to extract $filename\n"; rm "$filename"; exit 1; }
+    curl -LO "$url" || { logging "error" "Failed to download: $url" "red"; exit 1; }
+    logging "info" "Unzip: $filename" "cyan"
+    tar -xzf "$filename" || { logging "error" "Failed to extract $filename" "red"; rm "$filename"; exit 1; }
     rm "$filename"
     # Assuming the extracted folder contains binaries to add to system bin directory
-    printf "\e[32m [+]\e[0m installing file: $filename\n"
-    sudo cp -r "./$package_name" "/usr/local/bin/"
+    logging "info" "Installing file: $filename" "cyan"
+    sudo cp -r "./$package_name" "/usr/local/bin/" || { logging "error" "Failed to install $filename" "red"; rm "./$package_name"; exit 1; }
     rm "./$package_name"
-    printf "\e[32m [+]\e[0m setting file: $filename\n"
+    logging "info" "Setting file: $filename" "cyan"
     chmod +x "/usr/local/bin/$package_name"
     printf "\e[34m[+]\e[0m installed: $package_name\n"
+    logging "info" "installed: $package_name" "cyan"
 }
 
 logging() {
 
     local mode="$1"
     local message="$2"
-    case $mode in
-        "step")
-            printf "\e[34m==>\e[0m $message\n"
+    local color="$3"
+    local color_code
+    case $color in
+        "red")
+            color_code="31m"
             ;;
-        "info")
-            printf "\e[34m[+]\e[0m $message\n"
+        "orange")
+            color_code="33m"
             ;;
-        "warn")
-            printf "\e[33m[-]\e[0m $message\n"
+        "yellow")
+            color_code="33m"
             ;;
-        "error")
-            printf "\e[31m[!]\e[0m $message\n"
+        "green")
+            color_code="32m"
+            ;;
+        "cyan")
+            color_code="36m"
+            ;;
+        "blue")
+            color_code="34m"
+            ;;
+        "purple")
+            color_code="35m"
             ;;
         *)
-            printf "\e[31m[!]\e[0m Internal script error, unknown mode: $mode\n"
+            color_code="0m"
+            ;;
+    esac
+    case $mode in
+        "step")
+            printf "\e[$color_code==>\e[0m $message\n"
+            ;;
+        "info")
+            printf "\e[$color_code[+]\e[0m $message\n"
+            ;;
+        "warn")
+            printf "\e[$color_code[-]\e[0m $message\n"
+            ;;
+        "error")
+            printf "\e[$color_code[!]\e[0m $message\n"
+            ;;
+        *)
+            printf "\e[$color_code[!]\e[0m Internal script error, unknown mode: $mode\n"
             exit 1
             ;;
     esac
@@ -63,7 +92,7 @@ install_dependencies() {
     local dependencies
     dependencies=$(echo "$pkg_json" | jq -r '.dependencies | to_entries[] | .value')
     for url in $dependencies; do
-        logging "info" "Found Dependencies in JSON File: $url"
+        logging "info" "Found Dependencies in JSON File: $url" "cyan"
         install_dependencies "$url"
     done
 
@@ -75,30 +104,30 @@ install_dependencies() {
     url_of_software_for_this_os=$(echo "$pkg_json" | jq -r ".$target_key")
 
     if [ -n "$url_of_software_for_this_os" ]; then
-        logging "info" "Found Dependencies in JSON File: $url_of_software_for_this_os"
+        logging "info" "Found Dependencies in JSON File: $url_of_software_for_this_os" "cyan"
         download_and_install "$url_of_software_for_this_os"
     else
         local main_url
         main_url=$(echo "$pkg_json" | jq -r '.url')
-        logging "info" "Found Dependencies in JSON File: $main_url"
+        logging "info" "Found Dependencies in JSON File: $main_url" "cyan"
         download_and_install "$main_url"
     fi
 
-    logging "step" "Running setup script for '$url2'..."
+    logging "step" "Running setup script for '$url2'..." "cyan"
 
     local runscript=true
     local scripts
-    scripts=$(echo "$pkg_json" | jq -r '.script | to_entries[] | .value') || { printf "\e[31m[!]\e[0m Skip this because there is no setup script.\n"; runscript=false; }
+    scripts=$(echo "$pkg_json" | jq -r '.script | to_entries[] | .value') || { printf "\e[31m[!]\e[0m Skip this because there is no setup script.\n" "red"; runscript=false; }
 
     case $runscript in
         true)
             for script in $scripts; do
-                logging "step" "Running setup script: '$script'..."
+                logging "step" "Running setup script: '$script'..." "cyan"
                 eval "$script"
             done
             ;;
         *)
-            logging "step" "Skip Running Install script: all script"
+            logging "step" "Skip Running Install script: all script" "yellow"
             ;;
     esac
 }
@@ -139,15 +168,15 @@ case "$command" in
         latest_version=$(get_latest_version)
         if [[ "$cateyeversion" == "$latest_version" ]]; then
             echo "Current: cateye V$cateyeversion (Up to date)"
-            logging "info" "No update."
+            logging "info" "No update." "cyan"
         else
             echo "Current: cateye V$cateyeversion (latest: V$latest_version)"
-            logging "info" "Updating Cateye: $current_script"
+            logging "info" "Updating Cateye: $current_script" "cyan"
             current_script="$0"
-            logging "info" "Downloading latest script to $current_script"
+            logging "info" "Downloading latest script to $current_script" "cyan"
             curl -sS -o "$current_script" "https://dl.kamu.jp/cateye/cateye" || { printf "\e[31m[!] Failed to download latest script\e[0m\n"; exit 1; }
             chmod +x "$current_script"
-            logging "info" "Updated successfully."
+            logging "info" "Updated successfully." "cyan"
         fi
         ;;
     "version")
@@ -158,113 +187,113 @@ case "$command" in
         else
             echo "cateye V$cateyeversion (latest: V$latest_version)"
         fi
-        logging "step" "OS"
+        logging "step" "OS" "purple"
         echo "OS: $os_id"
-        logging "step" "PATH of Cateye"
+        logging "step" "PATH of Cateye" "purple"
         echo "PATH: $0"
-        logging "step" "Update of This version"
-        logging "info" "$cateyechanges"
+        logging "step" "Update of This version" "purple"
+        logging "info" "$cateyechanges" "cyan"
         ;;
     "install")
         if [ -n "$2" ]; then
-            logging "info" "The number of arguments is normal. Start the installation."
+            logging "info" "The number of arguments is normal. Start the installation." "cyan"
         else
-            logging "error" "Not enough arguments"
+            logging "error" "Not enough arguments" "red"
             exit 1
         fi
 
         os_id=$(get_os)
         package_name="$2"
-        logging "step" "Start the installation."
+        logging "step" "Start the installation." "purple"
         json_url="https://dl.kamu.jp/$package_name/pkg.json"
         pkg_json=$(curl -sS "$json_url") || { logging "error" "Failed to retrieve JSON File from $json_url"; exit 1; }
         dependencies=$(echo "$pkg_json" | jq -r '.dependencies | to_entries[] | .value')
         for url in $dependencies; do
-            logging "info" "Found external JSON File in JSON File: $url"
+            logging "info" "Found external JSON File in JSON File: $url" "cyan"
             install_dependencies "$url"
         done
         os_id=$(get_os)
         target_key="$os_id"
         result=$(echo "$pkg_json" | jq ". | has(\"$target_key\")")
         if [ "$result" == "true" ]; then
-            logging "info" "Found Main url in JSON File: $url_of_software_for_this_os"
+            logging "info" "Found Main url in JSON File: $url_of_software_for_this_os" "cyan"
             download_and_install "$url_of_software_for_this_os"
         else
             main_url=$(echo "$pkg_json" | jq -r '.url')
-            logging "info" "Found Main url in JSON File: $main_url"
+            logging "info" "Found Main url in JSON File: $main_url" "cyan"
             download_and_install "$main_url"
         fi
-        printf "\e[34m==>\e[0m Running setup script for '$package_name'...\n"
+        logging "step" "Running setup script for '$package_name'..." "purple"
         runscript=true
         scripts=$(echo "$pkg_json" | jq -r '.script | to_entries[] | .value') || { printf "\e[31m[!]\e[0m Skip this because there is no setup script.\n"; runscript=false; }
         case $runscript in
             true)
                 for script in $scripts; do
-                    logging "step" "Running setup script: '$script'..."
+                    logging "step" "Running setup script: '$script'..." "purple"
                     eval "$script"
                 done
                 ;;
             *)
-                logging "step" "Skip Running Install script."
+                logging "step" "Skip Running Install script." "yellow"
                 ;;
         esac
-        printf "\e[34m==>\e[0m Done.\n"
+        logging "step" "Done." "purple"
         latest_version=$(get_latest_version)
         if [[ "$cateyeversion" != "$latest_version" ]]; then
-            logging "info" "A newer version is available: V$latest_version"
-            logging "info" "Consider running: sudo cateye update\n"
+            logging "warn" "A newer version is available: V$latest_version" "yellow"
+            logging "warn" "Consider running: sudo cateye update" "yellow"
         fi
-        logging "info" "Installation of $package_name and that dependencies completed successfully"
+        logging "info" "Installation of $package_name and that dependencies completed successfully" "cyan"
         ;;
     "url")
-        package_name="$2"
-        if [ -n "$2" ] && [ -n "$3" ]; then
-            logging "info" "The number of arguments is normal. Start the installation from the URL."
+        if [ -n "$2" ]; then
+            logging "info" "The number of arguments is normal. Start the installation from the URL." "cyan"
         else
-            logging "error" "Not enough arguments"
+            logging "error" "Not enough arguments" "red"
             exit 1
         fi
-        package_url="$3"
-        logging "step" "Running from the URL."
+        package_url="$2"
+        logging "step" "Running from the URL." "purple"
         json_url="$package_url"
-        pkg_json=$(curl -sS "$json_url") || { logging "error" "Failed to retrieve JSON File from $json_url"; exit 1; }
+        pkg_json=$(curl -sS "$json_url") || { logging "error" "Failed to retrieve JSON File from $json_url" "red"; exit 1; }
+        package_name=$(echo "$pkg_json" | jq -r '.name')
         dependencies=$(echo "$pkg_json" | jq -r '.dependencies | to_entries[] | .value')
         for url in $dependencies; do
-            logging "info" "Found external JSON File in JSON File: $url"
+            logging "info" "Found external JSON File in JSON File: $url" "cyan"
             install_dependencies "$url"
         done
         os_id=$(get_os)
         target_key="$os_id"
         result=$(echo "$pkg_json" | jq ". | has(\"$target_key\")")
         if [ "$result" == "true" ]; then
-            logging "info" "Found Main url in JSON File: $url_of_software_for_this_os"
+            logging "info" "Found Main url in JSON File: $url_of_software_for_this_os" "cyan"
             download_and_install "$url_of_software_for_this_os"
         else
             main_url=$(echo "$pkg_json" | jq -r '.url')
-            logging "info" "Found Main url in JSON File: $main_url"
+            logging "info" "Found Main url in JSON File: $main_url" "cyan"
             download_and_install "$main_url"
         fi
-        logging "step" "Running setup script for '$package_name'..."
+        logging "step" "Running setup script for '$package_name'..." "purple"
         runscript=true
         scripts=$(echo "$pkg_json" | jq -r '.script | to_entries[] | .value') || { printf "\e[31m[!]\e[0m Skip this because there is no setup script.\n"; runscript=false; }
         case $runscript in
             true)
                 for script in $scripts; do
-                    logging "step" "Running setup script: '$script'..."
+                    logging "step" "Running setup script: '$script'..." "purple"
                     eval "$script"
                 done
                 ;;
             *)
-                logging "step" "Skip Running Install script."
+                logging "step" "Skip Running Install script." "yellow"
                 ;;
         esac
-        logging "step" "Done."
+        logging "step" "Done." "purple"
         latest_version=$(get_latest_version)
         if [[ "$cateyeversion" != "$latest_version" ]]; then
-            logging "warn" "A newer version is available: V$latest_version"
-            logging "warn" "Consider running: sudo cateye update"
+            logging "warn" "A newer version is available: V$latest_version" "yellow"
+            logging "warn" "Consider running: sudo cateye update" "yellow"
         fi
-        logging "info" "Installation of $package_name and that dependencies completed successfully"
+        logging "info" "Installation of $package_name and that dependencies completed successfully" "cyan"
         ;;
     "cedk")
         logging "step" "Running Cateye Development Kit..."
@@ -307,9 +336,9 @@ EOF
         ;;
 
     *)
-        logging "error" "Unknown command"
+        logging "error" "Unknown command" "red"
         echo " "
-        logging "step" "Usage"
+        logging "step" "Usage" "purple"
         echo "Update:"
         echo " sudo cateye update"
         echo "Run CEDK(Cateye Development Kit):"
@@ -317,7 +346,7 @@ EOF
         echo "Install from Kamu Dev:"
         echo " sudo cateye install [package name]"
         echo "Install from Other Site:"
-        echo " sudo cateye url [package name] [url of Kamu Package JSON]"
+        echo " sudo cateye url [url of Kamu Package JSON]"
         echo "Show version:"
         echo " sudo cateye version"
         ;;
